// EL PIÑA Training System
let CONFIG={},ROUNDS_DATA={},PLIO_DATA={};
let state={weeks:{},total:0},roundsDone={date:'',done:[]},rdSet=new Set();
let boxingTimer={running:false,interval:null,round:0,isWork:true,timeLeft:180};
let plioTimer={day:'diaA',block:'calent',running:false,interval:null,timeLeft:30,isWorkPhase:true,round:0,config:null};
let devTimer={running:false,interval:null,timeLeft:80},audioCtx=null;

async function initSystem(){try{const[c,r,p]=await Promise.all([fetch('data/system-config.json'),fetch('data/boxing-rounds.json'),fetch('data/plio-exercises.json')]);CONFIG=await c.json();ROUNDS_DATA=await r.json();PLIO_DATA=await p.json();loadState();renderAll();setupEventListeners();console.log('EL PIÑA:',CONFIG.version);}catch(e){console.error(e);loadDefaults();renderAll();}}

function loadDefaults(){CONFIG={version:'default',workDuration:180,restDuration:60,pinaThresholds:[2,4,7,10,14],pinaNames:['¡PRIMERA PIÑA!','¡PIÑA DOBLE!','¡PIÑA POWER!','¡SUPER PIÑA!','¡PIÑA SUPREMA! 菠萝']};ROUNDS_DATA={rounds:[{t:'Estabilidad',k:'Movimiento'}]};PLIO_DATA={diaA:{calent:{rounds:8,workSec:30,restSec:20,exs:['Skipping','Plancha']},finish:{rounds:10,workSec:30,restSec:45,exs:['Pushups','Squats']}},diaB:{calent:{rounds:8,workSec:30,restSec:20,exs:['Skipping']},finish:{rounds:10,workSec:35,restSec:45,exs:['Russian twist']}}};}
function loadState(){state=JSON.parse(localStorage.getItem('pina_state')||'{"weeks":{},"total":0}');roundsDone=JSON.parse(localStorage.getItem('pina_rounds')||'{"date":"","done":[]}');const t=new Date().toISOString().slice(0,10);rdSet=new Set(roundsDone.date===t?roundsDone.done:[]);}
function saveState(){localStorage.setItem('pina_state',JSON.stringify(state));}
function getAudioContext(){if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();return audioCtx;}
function beep(f,d,t='square',v=0.18,dl=0){const c=getAudioContext(),o=c.createOscillator(),g=c.createGain();o.type=t;o.frequency.value=f;g.gain.value=v;o.connect(g);g.connect(c.destination);const n=c.currentTime+dl;o.start(n);o.stop(n+d);}
function soundWork(){beep(523,0.12);beep(660,0.18,undefined,undefined,0.1);}
function soundRest(){beep(440,0.12);beep(330,0.18,undefined,undefined,0.1);}
function soundWarn(){beep(880,0.07);beep(880,0.07,undefined,undefined,0.18);beep(880,0.07,undefined,undefined,0.36);}
function soundRound(){beep(660,0.12);beep(784,0.2,undefined,undefined,0.1);}
function soundDone(){[523,659,784,1047].forEach((f,i)=>beep(f,0.25,undefined,0.15,i*0.14));}
function soundPina(){const c=getAudioContext(),t=c.currentTime,b=c.createBuffer(1,c.sampleRate*0.5,c.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length)*0.12;const s=c.createBufferSource();s.buffer=b;s.connect(c.destination);s.start(t);}

function getWeekStart(r){const d=new Date(r||new Date()),dy=d.getDay(),df=d.getDate()-dy+(dy===0?-6:1);return new Date(d.setDate(df));}
function getWeekKey(r){return getWeekStart(r).toISOString().slice(0,10);}
function calcStreak(){let st=0;const wks=Object.keys(state.weeks||{}).sort().reverse();for(const wk of wks){const ss=(state.weeks[wk]||[]);for(const s of[...ss].reverse()){if(s&&s.done)st++;else break;}}return st;}
function getWeekDayIndex(){const days=[1,2,3,4,5],td=new Date().getDay();return days.indexOf(td);}
function calcPinaLevel(total){let lvl=0;const th=CONFIG.pinaThresholds||[2,4,7,10,14];for(let i=0;i<th.length;i++){if(total>=th[i])lvl=i+1;}return lvl;}
function formatSessionDate(ds){const d=new Date(ds+'T12:00:00'),ms=['ENE','FEB','MAR','ABR','MAY','JUN','JUL','AGO','SEP','OCT','NOV','DIC'];return d.getDate()+' '+ms[d.getMonth()];}

const CIRC=515.2,WD=180,RD=60;
function toggleBoxing(){boxingTimer.running?stopBoxing():startBoxing();}
function startBoxing(){boxingTimer.running=true;document.getElementById('btnSS').textContent='⏸ PAUSA';document.getElementById('sweepEl').classList.add('go');boxingTimer.interval=setInterval(boxingTick,1000);displayBoxing();}
function stopBoxing(){boxingTimer.running=false;clearInterval(boxingTimer.interval);document.getElementById('btnSS').textContent='▶ INICIAR';document.getElementById('sweepEl').classList.remove('go');}
function resetBoxing(){stopBoxing();boxingTimer.round=0;boxingTimer.isWork=true;boxingTimer.timeLeft=WD;displayBoxing();updateRingDetail();}
function boxingTick(){boxingTimer.timeLeft--;if(boxingTimer.timeLeft<0){if(boxingTimer.isWork){soundRest();boxingTimer.isWork=false;boxingTimer.timeLeft=RD;}else{soundRound();boxingTimer.isWork=true;boxingTimer.round++;if(boxingTimer.round>=(ROUNDS_DATA.rounds?.length||9)){boxingDone();return;}boxingTimer.timeLeft=WD;}}displayBoxing();updateRingDetail();}
function boxingDone(){stopBoxing();soundDone();alert('🍍 ¡BOXING TERMINADO!');}
function displayBoxing(){const m=Math.floor(boxingTimer.timeLeft/60),s=boxingTimer.timeLeft%60,el=document.getElementById('tTime');el.textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');const ph=document.getElementById('tPhase'),rf=document.getElementById('ringFill'),warn=boxingTimer.isWork&&boxingTimer.timeLeft<=5;if(warn){el.className='ttime wc';ph.className='tphase w';ph.textContent='⚠ TERMINA';soundWarn();}else if(boxingTimer.isWork){el.className='ttime';ph.className='tphase w';ph.textContent='TRABAJO';}else{el.className='ttime rc';ph.className='tphase r';ph.textContent='DESCANSO';}const total=boxingTimer.isWork?WD:RD,pct=boxingTimer.timeLeft/total,dash=CIRC*pct;rf.style.strokeDashoffset=CIRC-dash;rf.className=boxingTimer.isWork?'ring-fill':'ring-fill restc';}
function updateRingDetail(){const r=ROUNDS_DATA.rounds?.[boxingTimer.round];if(r){document.getElementById('tdTitle').textContent=r.t||'Round '+(boxingTimer.round+1);document.getElementById('tdKeys').textContent=r.k||'';}}
function selectRound(i){if(boxingTimer.running)stopBoxing();boxingTimer.round=i;boxingTimer.isWork=true;boxingTimer.timeLeft=WD;displayBoxing();renderRounds();}

function setPlioDay(d){plioTimer.day=d;plioTimer.block='calent';stopPlio();resetPlio();renderPlioList();}
function setPlioBlock(b){plioTimer.block=b;stopPlio();resetPlio();renderPlioList();}
function getPlioConfig(){const d=PLIO_DATA[plioTimer.day];if(!d)return null;if(plioTimer.block==='calent'||plioTimer.block==='finish')return d[plioTimer.block];return d.dev||d.calent;}
function togglePlio(){plioTimer.running?stopPlio():startPlio();}
function startPlio(){plioTimer.config=getPlioConfig();if(!plioTimer.config)return;plioTimer.running=true;document.getElementById('btnPS').textContent='⏸ PAUSA';plioTimer.interval=setInterval(plioTick,1000);displayPlio();}
function stopPlio(){plioTimer.running=false;clearInterval(plioTimer.interval);document.getElementById('btnPS').textContent='▶ INICIAR';}
function resetPlio(){plioTimer.timeLeft=30;plioTimer.isWorkPhase=true;plioTimer.round=0;displayPlio();}
function plioTick(){plioTimer.timeLeft--;if(plioTimer.timeLeft<0){plioTimer.isWorkPhase=!plioTimer.isWorkPhase;if(plioTimer.isWorkPhase){plioTimer.round++;soundRound();if(plioTimer.round>=plioTimer.config.rounds){plioDone();return;}}plioTimer.timeLeft=plioTimer.isWorkPhase?plioTimer.config.workSec:plioTimer.config.restSec;}displayPlio();}
function plioDone(){stopPlio();soundDone();alert('🍍 ¡PLIO TERMINADO!');}
function displayPlio(){const m=Math.floor(plioTimer.timeLeft/60),s=plioTimer.timeLeft%60,tel=document.getElementById('ptTime');tel.textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');const ph=document.getElementById('ptPhase'),fill=document.getElementById('ptFill'),ex=document.getElementById('ptEx'),prog=document.getElementById('ptProg'),warn=plioTimer.isWorkPhase&&plioTimer.timeLeft<=5;if(warn){tel.className='pt-time wn';ph.className='pt-phase w';ph.textContent='⚠ TERMINA';}else if(plioTimer.isWorkPhase){tel.className='pt-time gn';ph.className='pt-phase w';ph.textContent='TRABAJO';}else{tel.className='pt-time';ph.className='pt-phase r';ph.textContent='DESCANSO';}const exIdx=plioTimer.round%plioTimer.config.exs.length;ex.textContent=plioTimer.config.exs[exIdx];prog.textContent='Round '+(plioTimer.round+1)+'/'+plioTimer.config.rounds;const total=plioTimer.isWorkPhase?plioTimer.config.workSec:plioTimer.config.restSec,pct=plioTimer.timeLeft/total;fill.style.width=pct*100+'%';fill.className=plioTimer.isWorkPhase?'pt-fill':'pt-fill gf';}

function startDev(secs){stopDev();devTimer.timeLeft=secs;devTimer.running=true;devTimer.interval=setInterval(devTick,1000);displayDev();soundWork();}
function stopDev(){devTimer.running=false;clearInterval(devTimer.interval);}
function devTick(){devTimer.timeLeft--;displayDev();if(devTimer.timeLeft<=0){stopDev();soundDone();}}
function displayDev(){const m=Math.floor(devTimer.timeLeft/60),s=devTimer.timeLeft%60;document.getElementById('devTime').textContent=String(m).padStart(2,'0')+':'+String(s).padStart(2,'0');}

function renderStats(){document.getElementById('statSessions').textContent=state.total||0;document.getElementById('statStreak').textContent=calcStreak();const wk=getWeekKey(),sess=(state.weeks[wk]||Array(5).fill(null)),completed=sess.filter(s=>s&&s.done).length;document.getElementById('statWeek').textContent=completed+'/5';document.getElementById('statLevel').textContent=calcPinaLevel(state.total||0);}
function renderPinaLevel(){const total=state.total||0,lvl=calcPinaLevel(total),stars=document.querySelectorAll('.pstar');stars.forEach((s,i)=>{if(i<lvl)s.classList.add('on');else s.classList.remove('on');});applyPinaMode(lvl);}
function applyPinaMode(lvl){if(lvl>=3)document.body.classList.add('pina-mode');else document.body.classList.remove('pina-mode');}
function renderWeek(){const wk=getWeekKey(),grid=document.getElementById('weekGrid'),sess=(state.weeks[wk]||Array(5).fill(null)),todayIdx=getWeekDayIndex();grid.innerHTML='';for(let i=0;i<5;i++){const s=sess[i]||{done:false,date:null},isPlio=(i===1||i===3),cal=isPlio?'CAL2':'CAL1',dl=s.date?formatSessionDate(s.date):'';const div=document.createElement('div');div.className='day'+(i===todayIdx?' today':'')+(s.done?' done':'');div.innerHTML='<div class="d-name">DÍA '+(i+1)+'</div><div class="d-num">'+dl+'</div><div class="d-tags"><span class="tag tb">BOX</span><span class="tag tp">'+cal+'</span></div><button class="chk'+(s.done?' on':'')+'" onclick="toggleSession('+i+')">✓</button>';grid.appendChild(div);}}
function toggleSession(idx){const wk=getWeekKey();if(!state.weeks[wk])state.weeks[wk]=Array(5).fill(null);const s=state.weeks[wk][idx],oldTotal=state.total||0;if(s&&s.done){state.weeks[wk][idx]=null;state.total=Math.max(0,oldTotal-1);}else{state.weeks[wk][idx]={done:true,date:new Date().toISOString().slice(0,10)};state.total=(oldTotal||0)+1;}saveState();const newTotal=state.total||0,oldLvl=calcPinaLevel(oldTotal),newLvl=calcPinaLevel(newTotal);if(newLvl>oldLvl&&newLvl>0)triggerPinaUp(newLvl);renderAll();}
function renderRounds(){const grid=document.getElementById('roundGrid');grid.innerHTML='';(ROUNDS_DATA.rounds||[]).forEach((r,i)=>{const done=rdSet.has(i),act=i===boxingTimer.round;const div=document.createElement('div');div.className='ri'+(act?' act':'')+(done?' dn':'');div.onclick=function(){selectRound(i);};div.innerHTML='<div class="ri-num">ROUND '+(i+1)+'</div><div class="ri-title">'+(r.t||'Ejercicio '+(i+1))+'</div>';grid.appendChild(div);});}
function renderPlioList(){const cont=document.getElementById('plioList'),data=PLIO_DATA[plioTimer.day];if(!data)return;let html='';const c=data.calent;html+=exHTML('calent','CALENTAMIENTO',c.rounds+'r · '+c.workSec+'s/'+c.restSec+'s','','');if(data.dev){const d=data.dev;html+=exHTML('dev','DESARROLLO',d.rounds+'r · '+d.workSec+'s/'+d.restSec+'s','',Array.isArray(d.links)?d.links[0]:'');}const f=data.finish;html+=exHTML('finish','FINISHER',f.rounds+'r · '+f.workSec+'s/'+f.restSec+'s','',Array.isArray(f.links)?f.links[0]:'');cont.innerHTML=html;}
function exHTML(id,name,detail,note,link){return '<div class="ex"><div class="ex-hdr" onclick="toggleEx(\''+id+'\')"><div><div class="ex-name">'+name+'</div><div class="ex-det">'+detail+'</div></div><span class="earr" id="'+id+'arr">▶</span></div><div class="ex-body" id="'+id+'body">'+(note?'<div class="ex-note">'+note+'</div>':'')+(link?'<a href="'+link+'" target="_blank" class="lnk">VER VIDEO →</a>':'')+'</div></div>';}
function toggleEx(id){const b=document.getElementById(id+'b'),a=document.getElementById(id+'arr');const o=b.classList.toggle('open');a.classList.toggle('open',o);}
function renderHistory(){let html='',cnt=0,ws=getWeekStart();for(let w=3;w>=0;w--){const ref=new Date(ws);ref.setDate(ws.getDate()-w*7);const wk=getWeekKey(ref),sess=(state.weeks||{})[wk]||Array(5).fill(null),isCur=(w===0);html+='<div class="hw"><div class="hwk">';for(let i=0;i<5;i++){const s=sess[i]||{done:false},isFut=isCur&&!s.done&&i>=getWeekDayIndex();let cn='hd ';if(isFut)cn+='fut';else if(s.done){cn+='hit';cnt++;}else cn+='miss';const tl=s.date||('Sesión '+(i+1));html+='<div class="'+cn+'" title="'+tl+'"></div>';}html+='</div></div>';}document.getElementById('histGrid').innerHTML=html;document.getElementById('histCount').textContent=cnt;}
function renderAll(){renderStats();renderPinaLevel();renderWeek();renderRounds();renderPlioList();renderHistory();}

function switchTab(name,btn){document.querySelectorAll('.tc').forEach(el=>el.classList.remove('on'));document.querySelectorAll('.tbtn').forEach(el=>el.classList.remove('on'));document.getElementById('tab-'+name).classList.add('on');btn.classList.add('on');}

function triggerPinaUp(lvl){const ov=document.getElementById('transOverlay'),fl=document.getElementById('transFlash'),ct=document.getElementById('transCenter');ov.style.display='block';fl.style.animation='flashAnim 0.6s ease-out forwards';ct.style.animation='centerPop 0.5s ease-out forwards';soundPina();setTimeout(function(){spawnSparks();},200);const ln=CONFIG.pinaNames?.[lvl-1]||'NIVEL '+lvl,ss='⭐'.repeat(lvl);ct.innerHTML='<div style="font-size:42px;margin-bottom:12px;">'+ss+'</div><div style="font-family:var(--fd);font-size:18px;color:var(--gold-l);text-shadow:var(--gg);">'+ln+'</div>';setTimeout(function(){ov.style.display='none';fl.style.animation='';ct.style.animation='';},2500);}
function spawnSparks(){const ct=document.getElementById('tcSparks');ct.innerHTML='';for(let i=0;i<50;i++){const s=document.createElement('div');s.className='spark';const ang=Math.random()*360,dist=80+Math.random()*220,dx=Math.cos(ang*Math.PI/180)*dist,dy=Math.sin(ang*Math.PI/180)*dist;s.style.setProperty('--dx',dx+'px');s.style.setProperty('--dy',dy+'px');s.style.animationDelay=Math.random()*0.3+'s';ct.appendChild(s);}}

function setupEventListeners(){document.querySelectorAll('.tbtn').forEach(btn=>{btn.addEventListener('click',function(){switchTab(this.getAttribute('data-tab'),this);});});document.getElementById('btnSS')?.addEventListener('click',toggleBoxing);document.getElementById('btnBR')?.addEventListener('click',resetBoxing);document.getElementById('btnPS')?.addEventListener('click',togglePlio);document.getElementById('btnPR')?.addEventListener('click',resetPlio);document.querySelectorAll('[data-dev-secs]').forEach(btn=>{btn.addEventListener('click',function(){startDev(parseInt(this.getAttribute('data-dev-secs')));});});document.addEventListener('keydown',function(e){if(e.code==='Space'&&document.activeElement.tagName!=='BUTTON'){e.preventDefault();const at=document.querySelector('.tc.on');if(at?.id==='tab-boxing')toggleBoxing();else if(at?.id==='tab-plio')togglePlio();}});}

document.addEventListener('DOMContentLoaded',initSystem);
